config/routes.rb
Rails.application.routes.draw do

  root 'application#home', page: 'home'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :bands do
    resources :opinions, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :reactions, only: [:create]
    end
    resources :events do
      resources :attendances, only: [:index, :create, :destroy]
    end
    resources :posts do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
    resources :albums do
      resources :tracks
    end
  end

  post '/bands/:band_id/add', to: 'bands#add_member', as: 'member_add'
  delete '/bands/:band_id/remove/:id', to: 'bands#remove_member', as: 'member_remove'

end

app/models/event.rb
# Event of a band, users can set their attendance.
class Event < ActiveRecord::Base
  belongs_to :band
  has_many :attendances
  
  before_validation :strip_whitespace
  
  validates :title, presence: true, length: { minimum: 3, maximum: 20 }, 
    format: { with: /\A[a-zA-Z0-9 _-]+\z/, message: "only allows letters, numbers, spaces, '-' and '_'" }
  validates :info, presence: true, length: { minimum: 3, maximum: 200 }
  validates :place, presence: true, length: { minimum: 3, maximum: 50 }
  validates :start_time, presence: true
  validate :start_time_is_not_in_past
  validates :duration, presence: true, numericality: { greater_than: 0 }
  
  def strip_whitespace
    self.title = self.title.strip unless self.title.nil?
    self.info = self.info.strip unless self.info.nil?
    self.place = self.place.strip unless self.place.nil?
  end
  
  def start_time_is_not_in_past
    errors.add(:start_time, "can't be in the past") if !start_time.blank? && start_time < Date.today
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :fetch_current_event, only: [:show, :edit, :update, :destroy]
  before_action :fetch_current_band
  before_action :user_is_member_of_band, only: [:new, :create, :edit, :update, :destroy]

  def index
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.band = @band

    if @event.save
       redirect_to band_event_path(@band, @event)
    else
      render 'new'
    end
  end

  def show
    temp = current_user.nil? ? [] : @event.attendances.select { |att| att.user_id == current_user.id }
    if temp.count > 0
      @is_going = true
      @attendance = temp[0]
    else
      @is_going = false
    end
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to band_event_path(@band, @event)
    else
      render 'edit'
    end
  end

  def destroy
    @event.attendances.each { |att| att.destroy }
    @event.destroy
    redirect_to band_events_path(@band)
  end

  protected

  def fetch_current_event
    @event = Event.find(params[:id])
  end

  def fetch_current_band
    @band = Band.find(params[:band_id])
  end
  
  def user_is_member_of_band
    @band = Band.find(params[:band_id])
    if current_user.band_id != @band.id
      flash[:alert] = "Access denied, you are not member of this band."
      redirect_to band_events_path(@band)
    end
  end

  def event_params
    params.require(:event).permit(:title, :start_time, :duration, :place, :info)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for [@band, @event] do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field form-group">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time, default: DateTime.now, start_year: DateTime.now.year, end_year: DateTime.now.year + 10 %>
  </div>
  <div class="field form-group">
    <%= f.label :duration %><br>
    <%= f.number_field :duration, min: 1 %>
  </div>
  <div class="field form-group">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="field form-group">
    <%= f.label :info %><br>
    <%= f.text_area :info %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to 'Cancel', band_events_path(@band), class: "btn btn-default" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= render "shared/band" %>

<h1>Edit Event</h1>

<%= render "form" %>

app/views/events/index.html.erb
<%= render "shared/band" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start time</th>
      <th>Duration</th>
      <th>Place</th>
    </tr>
  </thead>

  <tbody>
    <% @band.events.each do |event| %>
      <tr>
        <td><%= link_to event.title, band_event_path(@band, event) %></td>
        <td><%= event.start_time %></td>
        <td><%= event.duration %> min</td>
        <td><%= event.place %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if !current_user.nil? && current_user.band == @band %>
  <a role="button" class="btn btn-primary" href="<%= new_band_event_path %>">New Event</a>
<% end %>

app/views/events/new.html.erb
<%= render "shared/band" %>

<h1>New Event</h1>

<%= render "form" %>

app/views/events/show.html.erb
<%= render "shared/band" %>

<div class="col-md-7 col-lg-7">
  <table class="table">
    <tr>
      <th>Title:</th>
      <td><%= @event.title %></td>
    </tr>
    <tr>
      <th>Start time:</th>
      <td><%= @event.start_time %></td>
    </tr>
    <tr>
      <th>Duration:</th>
      <td><%= @event.duration %> min</td>
    </tr>
    <tr>
      <th>Place:</th>
      <td><%= @event.place %></td>
    </tr>
    <tr>
      <th>Info:</th>
      <td><%= @event.info %></td>
    </tr>
  </table>
  
  <% if user_signed_in? && current_user.band_id == @band.id %> 
    <%= link_to 'Edit', edit_band_event_path(@band, @event), class: "btn btn-primary" %>
    <%= link_to 'Delete', band_event_path(@band, @event), method: :delete, data: { confirm: 'Delete this event?' }, class: "btn btn-danger" %>
    <br><br>
  <% end %>
    
  <%= link_to 'Show Participants', band_event_attendances_path(@band, @event), class: "btn btn-default" %>
    
  <% if user_signed_in? %>
    <br><br>
    <% if @is_going %>
      <p>
        <%= button_to 'Cancel attendance', band_event_attendance_path(@band, @event, @attendance), method: :delete, class: "btn btn-danger" %>
      </p>
    <% else %>
      <p>
        <strong>Do you want to join?</strong>
        <%= button_to 'Join event', band_event_attendances_path(@band, @event), method: :post, action: 'create', class: "btn btn-primary" %>
      </p>
    <% end %>
  <% end %>
</div>