config/routes.rb
Rails.application.routes.draw do

  root 'application#home', page: 'home'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :bands do
    resources :opinions, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :reactions, only: [:create]
    end
    resources :events do
      resources :attendances, only: [:index, :create, :destroy]
    end
    resources :posts do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
    resources :albums do
      resources :tracks
    end
  end

  post '/bands/:band_id/add', to: 'bands#add_member', as: 'member_add'
  delete '/bands/:band_id/remove/:id', to: 'bands#remove_member', as: 'member_remove'

end

app/models/band.rb
# Consists of multiple users, is of one genre, has events, posts and albums, 
# user can write opinion on it
class Band < ActiveRecord::Base
  belongs_to :genre
  has_many :users
  has_many :events
  has_many :opinions
  has_many :posts
  has_many :albums
  
  before_validation :strip_whitespace
  
  validates :name, uniqueness: true, presence: true, length: { minimum: 3, maximum: 20 }, 
    format: { with: /\A[a-zA-Z0-9 _-]+\z/, message: "only allows letters, numbers, spaces, '-' and '_'" }
  validates :establish_year, presence: true
  validate :establish_year_is_not_in_future

  has_attached_file :cover_photo,
    :styles => { :medium => "300x300>", :thumb => "100x100#" },
    :default_url => "/images/:style/missing_band.png"
  validates_attachment_content_type :cover_photo, :content_type => /\Aimage\/.*\Z/
  
  def establish_year_is_not_in_future
    errors.add(:establish_year, "can't be in the future") if !establish_year.blank? && establish_year > Date.today.year
  end
  
  def strip_whitespace
    self.name = self.name.strip unless self.name.nil?
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :fetch_current_band, only: [:show, :edit, :update, :destroy]
  before_action :fetch_band_for_member, only: [:add_member, :remove_member]
  before_action :check_user_is_member_of_band, only: [:edit, :update, :destroy, :add_member, :remove_member]
  before_action :check_user_is_not_in_any_band, only: [:new, :create]
  before_action :fetch_genre_names, only: [:new, :create, :edit, :update]
  before_action :fetch_members_names, only: [:show]

  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    @band.genre = Genre.find_by_name(params[:band][:genre])
    # @band.users = [current_user]

    if @band.save
      current_user.update(band_id: @band.id)
      redirect_to @band
    else
      render 'new'
    end
  end

  def show
  end

  def edit
    @available = "["
    User.all.select{|user| user.band_id.nil?}.each_with_index do |u, i|
      @available << ", " if i > 0
      @available << '"' << u.username << '"'
    end
    @available << "]"
  end

  def update
    @band.genre = Genre.find_by_name(params[:band][:genre])

    if @band.update(band_params)
      redirect_to @band
    else
      render 'edit'
    end
  end

  def destroy
    @band.users.each { |user| user.update(:band_id => nil) }

    # destroying of other associated items

    @band.destroy
    redirect_to bands_path
  end

  def add_member
    @member = User.find_by_username(params[:username])
    if @member.nil?
      flash[:alert] = "User #{params[:username]} not found"
    else
      if @member.band != nil
        flash[:alert] = "User #{params[:username]} is already member of band #{@member.band.name}."
      else
        flash[:alert] = 'Error during adding user to band.' if !@member.update(:band_id => @band.id)
      end
    end

    redirect_to @band
  end

  def remove_member
    @member = User.find(params[:id])

    flash[:alert] = 'Error during removing member of band.' if !@member.update(:band_id => nil)

    redirect_to @band
  end

  protected

  def fetch_current_band
    @band = Band.find(params[:id])
  end

  def fetch_genre_names
    @genre_names = []
    Genre.all.each do |genre|
      @genre_names << genre.name
    end
  end

  def fetch_members_names
    @members = ""
    @band.users.each do |user|
      @members << ", " if @members.length > 0
      @members << user.username
    end
  end

  def fetch_band_for_member
    @band = Band.find(params[:band_id])
  end

  def check_user_is_not_in_any_band
    if current_user.band != nil
      flash[:alert] = "You are already in a band, you can't create another one."
      redirect_to current_user.band
    end
  end

  def check_user_is_member_of_band
    if @band.id != current_user.band_id
      flash[:alert] = "Access denied, you are not a member of this band."
      redirect_to @band
    end
  end

  def band_params
    params.require(:band).permit(:name, :establish_year, :cover_photo)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/edit.html.erb
<%= render "shared/band" %>

<h1>Edit Band</h1>

<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field form-group">
    <%= f.label :establish_year %><br>
    <%= f.number_field :establish_year, min: 1900, max: Time.now.year %>
  </div>
  <div class="field form-group">
    <%= f.label :genre %><br>
    <%= f.select :genre, @genre_names, selected: @band.genre.name %>
  </div>
  <div class="form-group">
    <%= f.label :cover_photo %>
    <%= f.file_field :cover_photo %>
  </div>

  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

<h2>Members</h2>
<div class="row">
  <div class=" col-lg-4 col-md-4">
    <table class="table">
      <thead>
        <tr>
          <th>Member username</th>
          <th colspan="1"></th>
        </tr>
      </thead>
      <tbody>
        <% @band.users.each do |member| %>
          <tr>
            <td><%= member.username %></td>
            <td><strong>
              <%= link_to 'X', member_remove_path(@band, member.id), method: :delete, style: "color: red", data: { confirm: 'Remove this member?' } %>
            </strong></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-md-5 col-lg5">
    <%= form_tag member_add_path(@band) do %>
      <div class="field form-group">
        <%= label_tag :username %><br>
        <%= select_tag :username, nil, id: "multiselect" %>
      </div>
      <div class="actions form-group">
        <%= submit_tag "Add member", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

<br>
<%= link_to 'Back', @band, class: "btn btn-default" %>

<script>
$("#multiselect").kendoMultiSelect({
  dataSource: {
    data: <%= raw @available %>
  },
  maxSelectedItems: 1
});
</script>

app/views/bands/index.html.erb
<% if !current_user.nil? && current_user.band.nil?%>
  <a role="button" class="btn btn-primary" href="<%= new_band_path %>">Create Your Own Band</a>
  <br><br>
<% end %>
<div class="container">
  <% @bands.each do |band| %>
    <div class="col-sm-4 col-lg-4 col-md-4">
      <div class="thumbnail">
        <%= link_to(image_tag(band.cover_photo.url(:medium), :class => "img-thumbnail", width: '250', height: '250'), band_path(band)) %>
        <div class="caption">
          <h4 class="pull-right"><%= band.genre.name %></h4>
          <h4><%= link_to band.name, band %></h4>
        </div>
        <div>
          <p class="pull-right"><%= band.events.count %> events</p>
          <p><%= band.albums.count %> albums</p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/bands/new.html.erb
<h1>New Band</h1>

<%= form_for(@band) do |f| %>
  <% if @band.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@band.errors.count, "error") %> prohibited this band from being saved:</h2>

      <ul>
      <% @band.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field form-group">
    <%= f.label :establish_year %><br>
    <%= f.number_field :establish_year, min: 1900, max: Time.now.year %>
  </div>
  <div class="field form-group">
    <%= f.label :genre %><br>
    <%= f.select :genre, @genre_names %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to 'Cancel', bands_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/bands/show.html.erb
<%= render "shared/band" %>

<div class="row">
  <div class="col-lg-5 col-md-5">
    <table class="table">
      <tr>
        <th>Name:</th>
        <td><%= @band.name %></td>
      </tr>
      <tr>
        <th>Establish year:</th>
        <td><%= @band.establish_year %></td>
      </tr>
      <tr>
        <th>Genre:</th>
        <td><%= @band.genre.name %></td>
      </tr>
      <tr>
        <th>Members:</th>
        <td><%= @members %></td>
      </tr>
    </table>

    <% if user_signed_in? && current_user.band_id == @band.id %>
      <a role="button" class="btn btn-primary" href="<%= edit_band_path(@band) %>">Edit Band</a>
    <% end %>
  </div>

  <div class="col-md-1 col-lg-1"></div>
  <div class="col-lg-5 col-md-5">
    <%= image_tag(@band.cover_photo.url(:medium), class: "img-responsive", width: '250', height: '250') %>
  </div>
</div>