config/routes.rb
Rails.application.routes.draw do

  root 'application#home', page: 'home'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :bands do
    resources :opinions, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :reactions, only: [:create]
    end
    resources :events do
      resources :attendances, only: [:index, :create, :destroy]
    end
    resources :posts do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
    resources :albums do
      resources :tracks
    end
  end

  post '/bands/:band_id/add', to: 'bands#add_member', as: 'member_add'
  delete '/bands/:band_id/remove/:id', to: 'bands#remove_member', as: 'member_remove'

end

app/models/post.rb
# Post (news) written by "band", can have comments written by users
class Post < ActiveRecord::Base
  belongs_to :band
  has_many :comments
  
  before_validation :strip_whitespace
  
  validates :title, presence: true, length: {minimum: 5, maximum: 30}
  validates :text, presence: true, length: {minimum: 10, maximum: 500}
  
  def strip_whitespace
    self.title = self.title.strip unless self.title.nil?
    self.text = self.text.strip unless self.text.nil?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :fetch_current_band
  before_action :fetch_current_post, only: [:show, :edit, :update, :destroy]
  before_action :check_user_is_member_of_band, only: [:new, :create, :edit, :update, :destroy]
  
  def index
  end
  
  def show
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.band_id = @band.id
    
    if @post.save
      redirect_to band_post_path(@band, @post)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      redirect_to band_post_path(@band, @post)
    else
      render 'edit'
    end    
  end
  
  def destroy
    @post.comments.each { |comment| comment.destroy }
    @post.destroy
    redirect_to band_posts_path(@band)
  end
  
  protected
  
  def fetch_current_band
    @band = Band.find(params[:band_id])
  end
  
  def fetch_current_post
    @post = Post.find(params[:id])
  end
  
  def check_user_is_member_of_band
    @band = Band.find(params[:band_id])
    if current_user.band_id != @band.id
      flash[:alert] = "Access denied, you are not member of this band."
      redirect_to band_posts_path(@band)
    end
  end
  
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@band, @post] do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field form-group">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to 'Cancel', band_posts_path(@band), class: "btn btn-default" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render "shared/band" %>

<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render "shared/band" %>

<div class="container">
  <% @band.posts.each do |post| %>
    <div class="row">
      <div class="col-md-8">
        <h2>
          <%= post.title %>
          <% if !current_user.nil? && current_user.band == @band %>
            <small><%= link_to 'Edit', edit_band_post_path(@band, post) %></small>
          <% end %>
        </h2>
        <p><span class="glyphicon glyphicon-time"></span> Posted on <%= post.created_at %></p>
        <hr>
        <p><%= post.text %></p>
        <%= link_to "Show comments (#{post.comments.count})", band_post_path(@band, post, anchor: 'comments'), class: "btn btn-default" %>
      </div>
    </div>
  <% end %>
  <hr>
  <% if !current_user.nil? && current_user.band == @band %>
    <a role="button" class="btn btn-primary" href="<%= new_band_post_path %>">New Post</a>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render "shared/band" %>

<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render "shared/band" %>

<h2><%= @post.title %></h2>

<div><%= @post.text %></div>

<div id="comments">
  <h3>Comments:</h3>
  <% @post.comments.each do |comment| %>
    <div class="media">
      <div class="pull-left">
        <% if comment.represents_band.nil? %>
          <%= image_tag(comment.user.avatar.url(:thumb), class: 'media-object', width: '64', height: '64') %>
        <% else %>
          <%= image_tag(Band.find(comment.represents_band).cover_photo.url(:thumb), class: 'media-object', width: '64', height: '64') %>
        <% end %>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <% if comment.represents_band.nil? %>
            <%= comment.user.username %>
          <% else %>
            <%= Band.find(comment.represents_band).name %>
          <% end %>
          <small><%= comment.created_at %></small>
          <% if user_signed_in? && (comment.user_id == current_user.id || (!current_user.band_id.nil? && comment.represents_band == current_user.band_id)) %>
          [ <%= link_to 'Edit', edit_band_post_comment_path(@band, @post, comment) %> |
            <%= link_to 'Delete', band_post_comment_path(@band, @post, comment), method: :delete, data: { confirm: 'Delete this comment?' } %> ]
          <% end %>
        </h4>
        <%= comment.text %>
      </div>
    </div>
  <% end %>
  <hr>
  <% if user_signed_in? %>
    <%= link_to 'Add Comment', new_band_post_comment_path(@band, @post), class: "btn btn-default" %>
  <% end %>
</div>