config/routes.rb
Rails.application.routes.draw do

  root 'application#home', page: 'home'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :bands do
    resources :opinions, only: [:index, :new, :create, :edit, :update, :destroy] do
      resources :reactions, only: [:create]
    end
    resources :events do
      resources :attendances, only: [:index, :create, :destroy]
    end
    resources :posts do
      resources :comments, only: [:new, :create, :edit, :update, :destroy]
    end
    resources :albums do
      resources :tracks
    end
  end

  post '/bands/:band_id/add', to: 'bands#add_member', as: 'member_add'
  delete '/bands/:band_id/remove/:id', to: 'bands#remove_member', as: 'member_remove'

end

app/models/album.rb
# Album of a band containing tracks
class Album < ActiveRecord::Base
  belongs_to :band
  has_many :tracks
  
  before_validation :strip_whitespace
  
  validates :title, presence: true, length: { minimum: 3, maximum: 20 }, 
    format: { with: /\A[a-zA-Z0-9 _-]+\z/, message: "only allows letters, numbers, spaces, '-' and '_'" }
  validates :release_date, presence: true
  validate :release_date_is_not_in_future
  
  has_attached_file :cover_photo,
    :styles => { :medium => "300x300>", :thumb => "100x100#" },
    :default_url => "/images/:style/missing_album_cover.png"
  validates_attachment_content_type :cover_photo, :content_type => /\Aimage\/.*\Z/
  
  def release_date_is_not_in_future
    errors.add(:release_date, "can't be in the future") if !release_date.blank? && release_date > Date.today
  end
  
  def strip_whitespace
    self.title = self.title.strip unless self.title.nil?
  end
end

app/models/attendance.rb
# Confirmed attendance of a user to an event of a band
class Attendance < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/models/band.rb
# Consists of multiple users, is of one genre, has events, posts and albums, 
# user can write opinion on it
class Band < ActiveRecord::Base
  belongs_to :genre
  has_many :users
  has_many :events
  has_many :opinions
  has_many :posts
  has_many :albums
  
  before_validation :strip_whitespace
  
  validates :name, uniqueness: true, presence: true, length: { minimum: 3, maximum: 20 }, 
    format: { with: /\A[a-zA-Z0-9 _-]+\z/, message: "only allows letters, numbers, spaces, '-' and '_'" }
  validates :establish_year, presence: true
  validate :establish_year_is_not_in_future

  has_attached_file :cover_photo,
    :styles => { :medium => "300x300>", :thumb => "100x100#" },
    :default_url => "/images/:style/missing_band.png"
  validates_attachment_content_type :cover_photo, :content_type => /\Aimage\/.*\Z/
  
  def establish_year_is_not_in_future
    errors.add(:establish_year, "can't be in the future") if !establish_year.blank? && establish_year > Date.today.year
  end
  
  def strip_whitespace
    self.name = self.name.strip unless self.name.nil?
  end
end

app/models/comment.rb
# Comment of user on a post written by "band"
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
  
  before_validation :strip_whitespace
  
  validates :text, presence: true, length: {minimum: 10, maximum: 150}
  
  def strip_whitespace
    self.text = self.text.strip unless self.text.nil?
  end
end

app/models/event.rb
# Event of a band, users can set their attendance.
class Event < ActiveRecord::Base
  belongs_to :band
  has_many :attendances
  
  before_validation :strip_whitespace
  
  validates :title, presence: true, length: { minimum: 3, maximum: 20 }, 
    format: { with: /\A[a-zA-Z0-9 _-]+\z/, message: "only allows letters, numbers, spaces, '-' and '_'" }
  validates :info, presence: true, length: { minimum: 3, maximum: 200 }
  validates :place, presence: true, length: { minimum: 3, maximum: 50 }
  validates :start_time, presence: true
  validate :start_time_is_not_in_past
  validates :duration, presence: true, numericality: { greater_than: 0 }
  
  def strip_whitespace
    self.title = self.title.strip unless self.title.nil?
    self.info = self.info.strip unless self.info.nil?
    self.place = self.place.strip unless self.place.nil?
  end
  
  def start_time_is_not_in_past
    errors.add(:start_time, "can't be in the past") if !start_time.blank? && start_time < Date.today
  end
end

app/models/genre.rb
# Every band has one genre
class Genre < ActiveRecord::Base
  has_many :bands
  
  validates :name, uniqueness: true, presence: true, length: { minimum: 3, maximum: 20 }
  
  def to_param
    name
  end
end

app/models/opinion.rb
# Opinion of user on a band, one user can have only one opinion on specific band, 
# users can have reactions on opinions (like / dislike)
class Opinion < ActiveRecord::Base
  belongs_to :user
  belongs_to :band
  has_many :reactions
  
  before_validation :strip_whitespace
  
  validates :text, presence: true, length: { minimum: 10, maximum: 100 }
  
  def strip_whitespace
    self.text = self.text.strip unless self.text.nil?
  end
end

app/models/post.rb
# Post (news) written by "band", can have comments written by users
class Post < ActiveRecord::Base
  belongs_to :band
  has_many :comments
  
  before_validation :strip_whitespace
  
  validates :title, presence: true, length: {minimum: 5, maximum: 30}
  validates :text, presence: true, length: {minimum: 10, maximum: 500}
  
  def strip_whitespace
    self.title = self.title.strip unless self.title.nil?
    self.text = self.text.strip unless self.text.nil?
  end
end

app/models/reaction.rb
# Reaction (like / dislike) of user on opinion on a band
class Reaction < ActiveRecord::Base
  belongs_to :user
  belongs_to :opinion
end

app/models/track.rb
# Track of one album of a band
class Track < ActiveRecord::Base
  belongs_to :album
  
  before_validation :strip_whitespace
  
  validates :title, presence: true, length: { minimum: 3, maximum: 20 }, 
    format: { with: /\A[a-zA-Z0-9 _-]+\z/, message: "only allows letters, numbers, spaces, '-' and '_'" }
  validates :number, presence: true, numericality: { greater_than: 0 }
  validate :numbers
  
  def numbers
    self.album.tracks.each do |track|
      if track.number == self.number && track.id != self.id
        errors.add(:number, "#{self.number} is already used in album #{self.album.title}")
      end
    end
  end
  
  def strip_whitespace
    self.title = self.title.strip unless self.title.nil?
  end
end

app/models/user.rb
# User of the system, can be in band, post opinions on bands, have reactions on other opinions, 
# attend events of bands, post comments on posts of bands
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  belongs_to :band
  has_many :opinions
  has_many :reactions
  has_many :attendances
  has_many :comments
  
  validates :username, uniqueness: true, presence: true, length: { minimum: 3, maximum: 20 }, 
    format: { with: /\A[a-zA-Z0-9]+\z/, message: "only allows letters and numbers" }
  validates :dob, presence: true
  validate :dob_is_in_past
  validate :username_is_allowed

  has_attached_file :avatar,
    :styles => { :medium => "300x300>", :thumb => "100x100#" },
    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def dob_is_in_past
    errors.add(:dob, "can't be in the future") if !dob.blank? && dob > Date.today
  end
  
  def username_is_allowed
    if !username.blank? && (username.downcase.include?('admin') || username.downcase.include?('administrator'))
      errors.add(:username, "#{username} is not allowed")
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2016.1.112/styles/kendo.common.min.css"/>
  <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2016.1.112/styles/kendo.rtl.min.css"/>
  <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2016.1.112/styles/kendo.silver.min.css"/>
  <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2016.1.112/styles/kendo.mobile.all.min.css"/>
  
  <script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
  <script src="https://kendo.cdn.telerik.com/2016.1.112/js/kendo.all.min.js"></script>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Home</a>
      </div>
      <ul class="nav navbar-nav">
        <li><a href="/bands">Bands</a></li>
        <% if user_signed_in? %>
          <li><%= link_to "My Band", current_user.band.nil? ? new_band_path : band_path(current_user.band) %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              Logged in as <strong><%= current_user.username %></strong>
              <span class="caret"></span>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
              </ul>
            </a>
          </li>
          <li><%= image_tag(current_user.avatar.url(:thumb), class: 'img-circle', width: '50', height: '50') %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
        <% end %>
    </ul>
    </div>
  </nav>

  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>

    <footer style="margin-top: 25px; margin-bottom: 25px; text-align: center">
      &copy; <%= Date.today.year %>
    </footer>
  </div>
</body>
</html>

app/views/shared/_band.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= band_path(@band) %>"><%= @band.name %></a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="<%= band_albums_path(@band) %>">Albums</a></li>
      <li><a href="<%= band_posts_path(@band) %>">Posts</a></li>
      <li><a href="<%= band_events_path(@band) %>">Events</a></li> 
      <li><a href="<%= band_opinions_path(@band) %>">Opinions</a></li> 
    </ul>
  </div>
</nav>